steps:

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: service-montecarlo
    args: ['build', '-t', 
           'europe-west3-docker.pkg.dev/$PROJECT_ID/greenpipeline/service-montecarlo:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: service-montecarlo
    args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/greenpipeline/service-montecarlo:$SHORT_SHA']

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: service-stocksim
    args: ['build', '-t', 
           'europe-west3-docker.pkg.dev/$PROJECT_ID/greenpipeline/service-stocksim:$SHORT_SHA', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    dir: service-stocksim
    args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/greenpipeline/service-stocksim:$SHORT_SHA']


  - id: 'run-tests'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds','triggers','run', 'run-integration-test', '--sha=$COMMIT_SHA']


# Store images in Google Artifact Registry
images:
  - europe-west3-docker.pkg.dev/$PROJECT_ID/greenpipeline/service-montecarlo:$SHORT_SHA
  - europe-west3-docker.pkg.dev/$PROJECT_ID/greenpipeline/service-stocksim:$SHORT_SHA