apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: green-pipeline
build:
  artifacts:
    - image: europe-west3-docker.pkg.dev/greenops-demo-env/greenpipeline/service-montecarlo
      context: service-montecarlo-py
      docker:
        dockerfile: Dockerfile
    - image: europe-west3-docker.pkg.dev/greenops-demo-env/greenpipeline/service-stocksim
      context: service-stocksim-py
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
  googleCloudBuild: {}
manifests:
  rawYaml:
    - integration-test/k8s-deploy-test.yaml
