apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocksim-app
  labels:
    app: stocksim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocksim-app
  template:
    metadata:
      labels:
        app: stocksim-app
    spec:
      containers:
      - name: stocksim-cnt
        image: europe-west3-docker.pkg.dev/PROJECT_ID/greenpipeline/service-stocksim:SHORT_SHA
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "0.4Gi" 
---
kind: Service
apiVersion: v1
metadata:
  name: stocksim-svc
spec:
  selector:
    app: stocksim-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: montecarlo-app
  labels:
    app: montecarlo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: montecarlo-app
  template:
    metadata:
      labels:
        app: montecarlo-app
    spec:
      containers:
      - name: montecarlo-cnt
        image: europe-west3-docker.pkg.dev/PROJECT_ID/greenpipeline/service-montecarlo:SHORT_SHA
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "0.4Gi" 
---
kind: Service
apiVersion: v1
metadata:
  name: montecarlo-svc
spec:
  selector:
    app: montecarlo-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080